-- CREAR TABLAS

CREATE TABLE CLIENTE (
    DNI NUMBER(8) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    TELEFONOS NUMBER(9),
    DIRECCION  VARCHAR2(50)
);

CREATE TABLE BILLETE (
    NROBILLETE VARCHAR2(5) PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA VARCHAR2(50) NOT NULL,
    ITINERARIO  VARCHAR2(40),
    DNI NUMBER(8),
    CONSTRAINT FK_DNI FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI)
);

CREATE TABLE COMPANIA (
    NROCOMPANIA VARCHAR2(5) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    NROBILLETE VARCHAR2(5),
    CONSTRAINT FK_NROBILLETE FOREIGN KEY (NROBILLETE) REFERENCES BILLETE(NROBILLETE)
);


-- INSERTAR REGISTROS
-- TABLA CLIENTE
INSERT INTO CLIENTE (DNI, NOMBRE, TELEFONOS, DIRECCION) 
VALUES (13789472, 'Juan Lopez', 987654321, 'Parque 19');

INSERT INTO CLIENTE (DNI, NOMBRE, TELEFONOS, DIRECCION) 
VALUES (23456789, 'Maria Lopez', 987654322, 'Los Pinos');

INSERT INTO CLIENTE (DNI, NOMBRE, TELEFONOS, DIRECCION) 
VALUES (34567890, 'Carlos Garcia', 987654323, 'Aproviser');

INSERT INTO CLIENTE (DNI, NOMBRE, TELEFONOS, DIRECCION) 
VALUES (45678901, 'Ana Torres', 987654324, 'Calle 5');

INSERT INTO CLIENTE (DNI, NOMBRE, TELEFONOS, DIRECCION) 
VALUES (56789012, 'Luis Martinez', 987654325, 'Calle Brazil');

-- TABLA BILLETE
INSERT INTO BILLETE (NROBILLETE, FECHA, HORA, ITINERARIO, DNI) 
VALUES ('B001', TO_DATE('2024-09-20', 'YYYY-MM-DD'), '10:00 AM', 'Lima - Cusco', 13789472);

INSERT INTO BILLETE (NROBILLETE, FECHA, HORA, ITINERARIO, DNI) 
VALUES ('B002', TO_DATE('2024-09-21', 'YYYY-MM-DD'), '12:00 PM', 'Cusco - Arequipa', 23456789);

INSERT INTO BILLETE (NROBILLETE, FECHA, HORA, ITINERARIO, DNI) 
VALUES ('B003', TO_DATE('2024-09-22', 'YYYY-MM-DD'), '03:00 PM', 'Arequipa - Lima', 34567890);

INSERT INTO BILLETE (NROBILLETE, FECHA, HORA, ITINERARIO, DNI) 
VALUES ('B004', TO_DATE('2024-09-23', 'YYYY-MM-DD'), '08:00 AM', 'Lima - Iquitos', 45678901);

INSERT INTO BILLETE (NROBILLETE, FECHA, HORA, ITINERARIO, DNI) 
VALUES ('B005', TO_DATE('2024-09-24', 'YYYY-MM-DD'), '06:00 PM', 'Iquitos - Cusco', 56789012);

-- TABLA COMPANIA
INSERT INTO COMPANIA (NROCOMPANIA, NOMBRE, NROBILLETE) 
VALUES ('C001', 'Aerolinea del Sol', 'B001');

INSERT INTO COMPANIA (NROCOMPANIA, NOMBRE, NROBILLETE) 
VALUES ('C002', 'Aerolinea Estelar', 'B002');

INSERT INTO COMPANIA (NROCOMPANIA, NOMBRE, NROBILLETE) 
VALUES ('C003', 'Aerolinea Rapida', 'B003');

INSERT INTO COMPANIA (NROCOMPANIA, NOMBRE, NROBILLETE) 
VALUES ('C004', 'Aerolinea Andina', 'B004');

INSERT INTO COMPANIA (NROCOMPANIA, NOMBRE, NROBILLETE) 
VALUES ('C005', 'Aerolinea Maritima', 'B005');

-- Solicitar Datos
SELECT * FROM CLIENTE;

SELECT * FROM BILLETE;

SELECT * FROM COMPANIA;

-- Consultas aplicando UPDATE, DELETE
UPDATE CLIENTE
SET TELEFONOS = 987654999
WHERE DNI = 13789472;

UPDATE CLIENTE
SET DIRECCION = 'Avenida 233'
WHERE DNI = 23456789;

UPDATE BILLETE
SET HORA = '11:00 AM'
WHERE NROBILLETE = 'B002';

DELETE FROM BILLETE
WHERE NROBILLETE = 'B003';

DELETE FROM CLIENTE
WHERE DNI = 45678901;

-- FUNCIONES
CREATE OR REPLACE FUNCTION contar_billetes_cliente(dni_cliente NUMBER)
RETURN NUMBER
IS
    v_contador NUMBER;
BEGIN
    -- Contar el n�mero de billetes comprados por el cliente
    SELECT COUNT(*)
    INTO v_contador
    FROM BILLETE
    WHERE DNI = dni_cliente;

    RETURN v_contador;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0; -- Retornar 0 si no hay billetes
    WHEN OTHERS THEN
        RETURN -1; -- Retornar -1 en caso de error
END contar_billetes_cliente;

SELECT contar_billetes_cliente(13789472) AS total_billetes FROM dual;

-- 3 Funciones Parte 1
SELECT UPPER (NOMBRE) FROM CLIENTE;

SELECT LENGTH(NOMBRE) FROM COMPANIA;

SELECT SUBSTR(DNI, 6, 8) FROM CLIENTE;

-- 3 Funciones Parte 2

SELECT NOMBRE, TO_DATE('2024-09-20', 'YYYY-MM-DD') AS FECHA_CONVERTIDA
FROM CLIENTE;

SELECT NROBILLETE, TO_CHAR(FECHA, 'DD-MON-YYYY') AS FECHA_FORMATO
FROM BILLETE;

SELECT NOMBRE, TO_NUMBER('987654321') AS TELEFONO_CONVERTIDO
FROM CLIENTE;




